objects: true

parking:
    enabled: false
    size: 0.3
    pos:
        x: 0.0
        y: 0.0
    angle: 0.0



start:
    pos:
        x: 0.0
        y: 0.0
    angle: 0

towers:
    -   color: "Red"
        pos:
            x: 1.1
            y: 0.5
    -   color: "Green"
        pos:
            x: 1.1
            y: 1.5
    -   color: "Green"
        pos:
            x: 0.5
            y: 1.9
    -   color: "Red"
        pos:
            x: -0.5
            y: 1.9
    -   color: "Red"
        pos:
            x: -1.1
            y: 1
    -   color: "Green"
        pos:
            x: -0.5
            y: 0.1
